import { expect, test } from "@playwright/test";

test("daily and weekly share one activity tab with stable layout and persistent claims", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript(() => {
    if (localStorage.getItem("idle-rpg-save-v1")) return;
    const key = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
    const today = new Date(); if (today.getHours() < 5) today.setDate(today.getDate() - 1);
    const monday = new Date(today); monday.setDate(monday.getDate() - (monday.getDay() + 6) % 7);
    localStorage.setItem("idle-rpg-save-v1", JSON.stringify({ version: 1, tutorialCompleted: true, gold: 0, gems: 300, lastActiveAt: Date.now(), updatedAt: Date.now(), settings: { soundEnabled: false, reducedMotion: true }, recurringTasks: {
      daily: { key: key(today), progress: { victory: 10, loot: 1, purchase: 1, alchemy: 1, hero_level: 1 }, claimed: [], milestones: [] },
      weekly: { key: key(monday), progress: { victory: 100, expedition: 5, alchemy: 10, hero_level: 10, summon: 5, gem_fusion: 0 }, claimed: [], milestones: [] },
    } }));
  });
  await page.goto("/");
  const entry = page.locator('[data-action="activities"]').first();
  await entry.click();
  const modal = page.getByRole("region", { name: "活动", exact: true });
  const frame = (await page.locator('.overlay-layer').boundingBox())!;
  const activity = (await modal.boundingBox())!;
  expect(Math.abs(activity.width - frame.width)).toBeLessThanOrEqual(1);
  expect(Math.abs(activity.height - frame.height)).toBeLessThanOrEqual(1);
  expect(Math.abs(activity.x - frame.x)).toBeLessThanOrEqual(1);
  expect(Math.abs(activity.y - frame.y)).toBeLessThanOrEqual(1);
  await expect(page.getByRole('dialog', { name: '活动', exact: true })).toHaveCount(0);
  await expect(page.locator('.modal-backdrop')).toHaveCount(0);
  await expect(page.locator('.battle-frame')).toBeHidden();
  await expect(page.locator('.bottom-nav')).toBeHidden();
  const resources = modal.getByRole('group', { name: '资源', exact: true });
  await expect(resources.locator('[data-activity-currency]')).toHaveCount(3);
  await expect(resources.locator('[data-activity-currency="gems"]')).toHaveAttribute('aria-label', '星石 300');
  const signInBox = (await modal.boundingBox())!;
  const verifyTaskListScroll = async () => {
    const list = page.locator('.recurring-task-list');
    const fixed = page.locator('.task-activity');
    const before = (await fixed.boundingBox())!;
    await page.locator('.recurring-task').last().scrollIntoViewIfNeeded();
    expect(await list.evaluate(element => element.scrollTop)).toBeGreaterThan(0);
    expect((await fixed.boundingBox())!.y).toBe(before.y);
    expect(await page.locator('.tasks-content').evaluate(element => element.scrollTop)).toBe(0);
    expect(await modal.evaluate(element => element.scrollTop)).toBe(0);
    await list.evaluate(element => { element.scrollTop = 0; });
  };
  await page.getByRole("tab", { name: "日常任务", exact: true }).click();
  const dailyBox = (await modal.boundingBox())!;
  expect(Math.abs(dailyBox.height - signInBox.height)).toBeLessThanOrEqual(1);
  expect(Math.abs(dailyBox.y - signInBox.y)).toBeLessThanOrEqual(1);
  await expect(page.locator('.recurring-task')).toHaveCount(7);
  await verifyTaskListScroll();
  await expect(page.locator('.recurring-task[data-task-id="login"], .recurring-task[data-task-id="salvage"]')).toHaveCount(0);
  await expect(page.getByRole('tab', { name: '每日', exact: true })).toHaveAttribute('aria-selected', 'true');
  const dailyTab = (await page.getByRole('tab', { name: '每日', exact: true }).boundingBox())!;
  const weeklyTab = (await page.getByRole('tab', { name: '每周', exact: true }).boundingBox())!;
  expect(await page.getByRole('tab', { name: '每日', exact: true }).evaluate((element) => (element as HTMLElement).offsetHeight)).toBeLessThanOrEqual(36);
  expect(dailyTab.y).toBe(weeklyTab.y);
  expect(Math.abs(dailyTab.width - weeklyTab.width)).toBeLessThanOrEqual(1);
  await expect(page.locator('.tasks-reset-note')).toHaveText('每日凌晨5点重置');
  await expect(page.locator('.task-activity-heading .tasks-reset-note')).toBeVisible();
  await expect(page.getByText('领取5项即可拿满')).toHaveCount(0);
  const heading = (await page.locator('.task-activity-heading').boundingBox())!;
  const reset = (await page.locator('.tasks-reset-note').boundingBox())!;
  expect(reset.y + reset.height).toBeLessThanOrEqual(heading.y + heading.height);
  await expect(page.locator('.task-node-value')).toHaveText(['40', '80', '100']);
  await expect(page.locator('.task-milestone .task-reward')).toHaveCount(0);
  const track = (await page.getByRole('progressbar', { name: '活跃度' }).boundingBox())!;
  let previousRight = 0;
  for (const points of [40, 80, 100]) {
    const chest = (await page.locator(`[data-action="task-milestone-tips"][data-points="${points}"]`).boundingBox())!;
    expect(Math.abs(chest.x + chest.width / 2 - (track.x + track.width * points / 100))).toBeLessThan(2);
    expect(chest.y).toBeGreaterThan(track.y + track.height);
    expect(chest.x).toBeGreaterThan(previousRight);
    previousRight = chest.x + chest.width;
  }
  await page.screenshot({ path: testInfo.outputPath("daily-tasks.png") });
  await page.locator('[data-action="task-milestone-tips"][data-points="40"]').click();
  const tips = page.getByRole('tooltip', { name: '活跃度宝箱奖励', exact: true });
  await expect(tips).toContainText('随机材料箱');
  await expect(tips).toContainText('尚未达成 · 0/40');
  await expect(tips.locator('button')).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath('activity-chest-tips.png') });
  await page.keyboard.press('Escape');
  await expect(tips).toBeHidden();
  await expect(modal).toBeVisible();
  for (const id of ["victory", "loot", "purchase", "alchemy", "hero_level"]) await page.locator(`.recurring-task[data-task-id="${id}"] button`).click();
  await expect(page.getByRole('progressbar', { name: '活跃度' })).toHaveAttribute('aria-valuenow', '100');
  await expect(page.locator('.recurring-task:not(.is-claimed)')).toHaveCount(2);
  await expect(resources.locator('[data-activity-currency="gold"] b')).toHaveText('5,000');
  for (const points of [40, 80, 100]) {
    const chest = page.locator(`[data-action="task-milestone-tips"][data-points="${points}"]`);
    await chest.click();
    await expect(tips).toBeHidden();
    await expect(chest).toHaveClass(/is-claimed/);
    await chest.click();
    await expect(tips).toBeVisible();
    await expect(tips).toContainText('已领取');
    await expect(tips.locator('button')).toHaveCount(0);
    const box = (await tips.boundingBox())!;
    expect(box.x).toBeGreaterThanOrEqual(dailyBox.x);
    expect(box.x + box.width).toBeLessThanOrEqual(dailyBox.x + dailyBox.width);
    expect(box.y + box.height).toBeLessThanOrEqual(dailyBox.y + dailyBox.height);
    await chest.click();
    await expect(tips).toBeHidden();
  }
  await page.getByRole('tab', { name: '每周', exact: true }).click();
  await expect(page.locator('.recurring-task')).toHaveCount(8);
  await verifyTaskListScroll();
  await expect(page.locator('.recurring-task[data-task-id="summon"], .recurring-task[data-task-id="gem_fusion"]')).toHaveCount(2);
  await expect(page.locator('.recurring-task[data-task-id="loot"], .recurring-task[data-task-id="purchase"]')).toHaveCount(0);
  await expect(resources.locator('[data-activity-currency="gems"]')).toHaveAttribute('aria-label', '星石 380');
  await expect(page.locator('.tasks-reset-note')).toHaveText('每周一凌晨5点重置');
  expect(Math.abs((await modal.boundingBox())!.height - dailyBox.height)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: testInfo.outputPath("weekly-tasks.png") });
  await expect(page.getByRole('progressbar', { name: '活跃度' })).toHaveAttribute('aria-valuenow', '0');
  await page.getByRole('tab', { name: '每日', exact: true }).click();
  await expect(page.locator('.task-milestone.is-claimed')).toHaveCount(3);
  await page.keyboard.press('Escape');
  await page.reload();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('idle-rpg-save-v1')!));
  expect(saved.recurringTasks.daily.claimed).toHaveLength(5);
  expect(saved.recurringTasks.weekly.claimed).toHaveLength(0);
  expect(saved.adTickets).toBe(1);
  expect(saved.gems).toBe(380);
  expect(saved.rewardBoxes).toEqual({ gem_box: 2, material_box: 1 });
  await entry.click();
  await page.getByRole('tab', { name: '日常任务', exact: true }).click();
  await page.getByRole('tab', { name: '每周', exact: true }).click();
  await page.locator('.recurring-task[data-task-id="gem_fusion"] button').click();
  await expect(modal).toHaveCount(0);
  await expect(page.locator('.battle-frame')).toBeVisible();
  await expect(page.locator('[data-action="select-tab"][data-tab="alchemy"]')).toHaveAttribute('aria-current', 'page');
  expect(errors).toEqual([]);
});
