import type { UnitState } from "../../src/simulation/types";

export function makeUnit(patch: Partial<UnitState> = {}): UnitState {
  return {
    id: "unit",
    team: "heroes",
    sourceId: "H01",
    name: "测试单位",
    x: 100,
    y: 0,
    hp: 100,
    maxHp: 100,
    rage: 100,
    maxRage: 100,
    attack: 100,
    defense: 10,
    damageElement: "physical",
    critChance: 0.05,
    attackMode: "melee",
    attackRange: 60,
    moveSpeed: 100,
    attackIntervalMs: 1000,
    castSpeedPct: 0,
    attackCooldownMs: 0,
    skillTriggerMs: 0,
    skillPrepareMs: null,
    skillCastDurationMs: null,
    skillCastId: null,
    skillCastSequence: 0,
    skillTargetIds: [],
    targetId: null,
    shield: 0,
    statuses: [],
    periodicEffects: [],
    alive: true,
    basicAttackCount: 0,
    skillCastCount: 0,
    chosenSkillId: null,
    passiveFlags: {},
    ...patch,
  };
}
