import type { DamageElement } from "../simulation/types";

export interface HeroDamageIdentity {
  id: string;
  name: string;
  damageSchool: "physical" | "magic";
  damageElement: DamageElement;
}

/** Playable H01–H80 (one per class×gender art). One school and one element per hero. */
export const HERO_DAMAGE_IDENTITIES: readonly HeroDamageIdentity[] = [
  { id: "H01", name: "洛恩", damageSchool: "physical", damageElement: "physical" },
  { id: "H02", name: "布兰", damageSchool: "physical", damageElement: "physical" },
  { id: "H03", name: "米娅", damageSchool: "magic", damageElement: "fire" },
  { id: "H04", name: "诺拉", damageSchool: "magic", damageElement: "holy" },
  { id: "H05", name: "塔林", damageSchool: "physical", damageElement: "physical" },
  { id: "H06", name: "乌鸦", damageSchool: "physical", damageElement: "dark" },
  { id: "H07", name: "塞拉", damageSchool: "magic", damageElement: "frost" },
  { id: "H08", name: "海泽", damageSchool: "magic", damageElement: "lightning" },
  { id: "H09", name: "莫尔", damageSchool: "physical", damageElement: "dark" },
  { id: "H10", name: "伊芙", damageSchool: "physical", damageElement: "frost" },
  { id: "H11", name: "维恩", damageSchool: "magic", damageElement: "dark" },
  { id: "H12", name: "凯恩", damageSchool: "physical", damageElement: "dark" },
  { id: "H13", name: "黛拉", damageSchool: "physical", damageElement: "fire" },
  { id: "H14", name: "薇尔", damageSchool: "magic", damageElement: "dark" },
  { id: "H15", name: "月桑", damageSchool: "magic", damageElement: "dark" },
  { id: "H16", name: "里芙", damageSchool: "physical", damageElement: "physical" },
  { id: "H17", name: "托尔", damageSchool: "physical", damageElement: "physical" },
  { id: "H18", name: "露芽", damageSchool: "magic", damageElement: "frost" },
  { id: "H19", name: "赤鳞", damageSchool: "magic", damageElement: "fire" },
  { id: "H20", name: "翠环", damageSchool: "magic", damageElement: "frost" },
  { id: "H21", name: "安珀", damageSchool: "physical", damageElement: "fire" },
  { id: "H22", name: "霍克", damageSchool: "physical", damageElement: "physical" },
  { id: "H23", name: "卡恩", damageSchool: "physical", damageElement: "physical" },
  { id: "H24", name: "伊琳", damageSchool: "magic", damageElement: "dark" },
  { id: "H25", name: "杜衡", damageSchool: "physical", damageElement: "physical" },
  { id: "H26", name: "岚纱", damageSchool: "magic", damageElement: "frost" },
  { id: "H27", name: "凌风", damageSchool: "physical", damageElement: "physical" },
  { id: "H28", name: "奥琳", damageSchool: "magic", damageElement: "lightning" },
  { id: "H29", name: "加伦", damageSchool: "magic", damageElement: "lightning" },
  { id: "H30", name: "雷默", damageSchool: "physical", damageElement: "lightning" },
  { id: "H31", name: "克莱", damageSchool: "magic", damageElement: "lightning" },
  { id: "H32", name: "墨薇", damageSchool: "magic", damageElement: "dark" },
  { id: "H33", name: "柯特", damageSchool: "physical", damageElement: "physical" },
  { id: "H34", name: "幽翎", damageSchool: "physical", damageElement: "dark" },
  { id: "H35", name: "图鲁", damageSchool: "physical", damageElement: "lightning" },
  { id: "H36", name: "娜薇", damageSchool: "magic", damageElement: "frost" },
  { id: "H37", name: "格蕾", damageSchool: "magic", damageElement: "dark" },
  { id: "H38", name: "摩恩", damageSchool: "magic", damageElement: "dark" },
  { id: "H39", name: "索尔", damageSchool: "magic", damageElement: "fire" },
  { id: "H40", name: "卡尔", damageSchool: "physical", damageElement: "physical" },
{ id: "H41", name: "艾拉", damageSchool: "physical", damageElement: "dark" },
  { id: "H42", name: "布伦", damageSchool: "physical", damageElement: "frost" },
  { id: "H43", name: "达恩", damageSchool: "magic", damageElement: "dark" },
  { id: "H44", name: "黛拉", damageSchool: "physical", damageElement: "dark" },
  { id: "H45", name: "费恩", damageSchool: "physical", damageElement: "fire" },
  { id: "H46", name: "格雷", damageSchool: "physical", damageElement: "dark" },
  { id: "H47", name: "哈尔", damageSchool: "magic", damageElement: "frost" },
  { id: "H48", name: "希拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H49", name: "乔恩", damageSchool: "physical", damageElement: "physical" },
  { id: "H50", name: "贾拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H51", name: "莱恩", damageSchool: "magic", damageElement: "frost" },
  { id: "H52", name: "诺恩", damageSchool: "magic", damageElement: "fire" },
  { id: "H53", name: "欧文", damageSchool: "magic", damageElement: "holy" },
  { id: "H54", name: "妮拉", damageSchool: "magic", damageElement: "holy" },
  { id: "H55", name: "奥拉", damageSchool: "physical", damageElement: "lightning" },
  { id: "H56", name: "皮拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H57", name: "琪拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H58", name: "瑞拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H59", name: "萨拉", damageSchool: "magic", damageElement: "lightning" },
  { id: "H60", name: "文恩", damageSchool: "magic", damageElement: "frost" },
  { id: "H61", name: "阿伦", damageSchool: "magic", damageElement: "frost" },
  { id: "H62", name: "贝拉", damageSchool: "magic", damageElement: "frost" },
  { id: "H63", name: "达恩", damageSchool: "magic", damageElement: "frost" },
  { id: "H64", name: "黛拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H65", name: "费恩", damageSchool: "magic", damageElement: "holy" },
  { id: "H66", name: "菲拉", damageSchool: "magic", damageElement: "holy" },
  { id: "H67", name: "吉拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H68", name: "伊恩", damageSchool: "magic", damageElement: "holy" },
  { id: "H69", name: "乔恩", damageSchool: "magic", damageElement: "holy" },
  { id: "H70", name: "凯恩", damageSchool: "magic", damageElement: "dark" },
  { id: "H71", name: "卡拉", damageSchool: "physical", damageElement: "dark" },
  { id: "H72", name: "莱拉", damageSchool: "physical", damageElement: "physical" },
  { id: "H73", name: "欧文", damageSchool: "physical", damageElement: "dark" },
  { id: "H74", name: "妮拉", damageSchool: "magic", damageElement: "lightning" },
  { id: "H75", name: "奎恩", damageSchool: "magic", damageElement: "lightning" },
  { id: "H76", name: "雷恩", damageSchool: "magic", damageElement: "lightning" },
  { id: "H77", name: "琪拉", damageSchool: "magic", damageElement: "lightning" },
  { id: "H78", name: "特恩", damageSchool: "magic", damageElement: "dark" },
  { id: "H79", name: "乌恩", damageSchool: "physical", damageElement: "physical" },
  { id: "H80", name: "蒂拉", damageSchool: "physical", damageElement: "physical" },
] as const;
