import type { DamageElement } from "../simulation/types";

export interface HeroDamageIdentity {
  id: string;
  name: string;
  damageSchool: "physical" | "magic";
  damageElement: DamageElement;
}

/** Playable H01–H80 (one per class×gender art). One school and one element per hero. */
export const HERO_DAMAGE_IDENTITIES: readonly HeroDamageIdentity[] = [
  { id: "H01", name: "罗德里克", damageSchool: "physical", damageElement: "physical" },
  { id: "H02", name: "格雷戈尔", damageSchool: "physical", damageElement: "physical" },
  { id: "H03", name: "艾琳娜", damageSchool: "magic", damageElement: "fire" },
  { id: "H04", name: "嘉芙莲", damageSchool: "magic", damageElement: "holy" },
  { id: "H05", name: "凯洛", damageSchool: "physical", damageElement: "physical" },
  { id: "H06", name: "维克托", damageSchool: "physical", damageElement: "dark" },
  { id: "H07", name: "伊芙琳", damageSchool: "magic", damageElement: "frost" },
  { id: "H08", name: "塔格尔", damageSchool: "magic", damageElement: "lightning" },
  { id: "H09", name: "沃尔克", damageSchool: "physical", damageElement: "dark" },
  { id: "H10", name: "赛琳", damageSchool: "physical", damageElement: "frost" },
  { id: "H11", name: "摩莉甘", damageSchool: "magic", damageElement: "dark" },
  { id: "H12", name: "塞洛", damageSchool: "physical", damageElement: "dark" },
  { id: "H13", name: "奈芙拉", damageSchool: "physical", damageElement: "fire" },
  { id: "H14", name: "瑟薇娅", damageSchool: "magic", damageElement: "dark" },
  { id: "H15", name: "塞西莉亚", damageSchool: "magic", damageElement: "dark" },
  { id: "H16", name: "海瑟", damageSchool: "physical", damageElement: "physical" },
  { id: "H17", name: "加雷斯", damageSchool: "physical", damageElement: "physical" },
  { id: "H18", name: "米露", damageSchool: "magic", damageElement: "frost" },
  { id: "H19", name: "阿格娜", damageSchool: "magic", damageElement: "fire" },
  { id: "H20", name: "塔莉丝", damageSchool: "magic", damageElement: "frost" },
  { id: "H21", name: "维奥拉", damageSchool: "physical", damageElement: "fire" },
  { id: "H22", name: "布鲁诺", damageSchool: "physical", damageElement: "physical" },
  { id: "H23", name: "奥斯卡", damageSchool: "physical", damageElement: "physical" },
  { id: "H24", name: "莫蕾", damageSchool: "magic", damageElement: "dark" },
  { id: "H25", name: "沈岳", damageSchool: "physical", damageElement: "physical" },
  { id: "H26", name: "苏霁", damageSchool: "magic", damageElement: "frost" },
  { id: "H27", name: "雷诺", damageSchool: "physical", damageElement: "physical" },
  { id: "H28", name: "萨琪", damageSchool: "magic", damageElement: "lightning" },
  { id: "H29", name: "奥伦", damageSchool: "magic", damageElement: "lightning" },
  { id: "H30", name: "阿凯隆", damageSchool: "physical", damageElement: "lightning" },
  { id: "H31", name: "赫克托", damageSchool: "magic", damageElement: "lightning" },
  { id: "H32", name: "梅莉莎", damageSchool: "magic", damageElement: "dark" },
  { id: "H33", name: "柯林", damageSchool: "physical", damageElement: "physical" },
  { id: "H34", name: "希尔达", damageSchool: "physical", damageElement: "dark" },
  { id: "H35", name: "玛蒂尔达", damageSchool: "physical", damageElement: "lightning" },
  { id: "H36", name: "乌尔萨", damageSchool: "magic", damageElement: "frost" },
  { id: "H37", name: "伊莎贝尔", damageSchool: "magic", damageElement: "dark" },
  { id: "H38", name: "塞缪尔", damageSchool: "magic", damageElement: "dark" },
  { id: "H39", name: "弗林特", damageSchool: "magic", damageElement: "fire" },
  { id: "H40", name: "坎贝尔", damageSchool: "physical", damageElement: "physical" },
  { id: "H41", name: "克蕾雅", damageSchool: "physical", damageElement: "dark" },
  { id: "H42", name: "瓦伦", damageSchool: "physical", damageElement: "frost" },
  { id: "H43", name: "德迦尔", damageSchool: "magic", damageElement: "dark" },
  { id: "H44", name: "妮克莎", damageSchool: "physical", damageElement: "dark" },
  { id: "H45", name: "达维恩", damageSchool: "physical", damageElement: "fire" },
  { id: "H46", name: "阿洛斯", damageSchool: "physical", damageElement: "dark" },
  { id: "H47", name: "奥瑞克", damageSchool: "magic", damageElement: "frost" },
  { id: "H48", name: "梅芙", damageSchool: "physical", damageElement: "physical" },
  { id: "H49", name: "巴尔克", damageSchool: "physical", damageElement: "physical" },
  { id: "H50", name: "梅芮", damageSchool: "physical", damageElement: "physical" },
  { id: "H51", name: "西尔凡", damageSchool: "magic", damageElement: "frost" },
  { id: "H52", name: "卡德罗斯", damageSchool: "magic", damageElement: "fire" },
  { id: "H53", name: "泽菲尔", damageSchool: "magic", damageElement: "holy" },
  { id: "H54", name: "诺薇雅", damageSchool: "magic", damageElement: "holy" },
  { id: "H55", name: "缇雅娜", damageSchool: "physical", damageElement: "lightning" },
  { id: "H56", name: "艾妲", damageSchool: "physical", damageElement: "physical" },
  { id: "H57", name: "温蒂", damageSchool: "physical", damageElement: "physical" },
  { id: "H58", name: "卡琳", damageSchool: "physical", damageElement: "physical" },
  { id: "H59", name: "露希娅", damageSchool: "magic", damageElement: "lightning" },
  { id: "H60", name: "埃利奥", damageSchool: "magic", damageElement: "frost" },
  { id: "H61", name: "程岱", damageSchool: "magic", damageElement: "frost" },
  { id: "H62", name: "叶青", damageSchool: "magic", damageElement: "frost" },
  { id: "H63", name: "云舟", damageSchool: "magic", damageElement: "frost" },
  { id: "H64", name: "林雀", damageSchool: "physical", damageElement: "physical" },
  { id: "H65", name: "莱昂纳", damageSchool: "magic", damageElement: "holy" },
  { id: "H66", name: "索菲娅", damageSchool: "magic", damageElement: "holy" },
  { id: "H67", name: "海伦娜", damageSchool: "physical", damageElement: "physical" },
  { id: "H68", name: "约书亚", damageSchool: "magic", damageElement: "holy" },
  { id: "H69", name: "西奥多", damageSchool: "magic", damageElement: "holy" },
  { id: "H70", name: "阿德里安", damageSchool: "magic", damageElement: "dark" },
  { id: "H71", name: "卡珊德拉", damageSchool: "physical", damageElement: "dark" },
  { id: "H72", name: "露比", damageSchool: "physical", damageElement: "physical" },
  { id: "H73", name: "诺兰", damageSchool: "physical", damageElement: "dark" },
  { id: "H74", name: "塔娜", damageSchool: "magic", damageElement: "lightning" },
  { id: "H75", name: "库尔坎", damageSchool: "magic", damageElement: "lightning" },
  { id: "H76", name: "巴图", damageSchool: "magic", damageElement: "lightning" },
  { id: "H77", name: "德洛莉丝", damageSchool: "magic", damageElement: "lightning" },
  { id: "H78", name: "马库斯", damageSchool: "magic", damageElement: "dark" },
  { id: "H79", name: "埃德蒙", damageSchool: "physical", damageElement: "physical" },
  { id: "H80", name: "芙蕾达", damageSchool: "physical", damageElement: "physical" },
] as const;
